#!/bin/bash

help() {
  echo "Config Builder Git"
  echo ""
  echo "Usage:"
  echo "  builder config git"
  echo ""
}

core() {
  config::git
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"