#!/bin/bash

help() {
  echo "Config Builder NPM"
  echo ""
  echo "Usage:"
  echo "  builder config npm"
  echo ""
}

core() {
  config::npm
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
