#!/bin/bash

help() {
  echo "Config Builder NPM"
  echo ""
  echo "Usage:"
  echo "  builder config npm"
  echo ""
}

core() {
  assert "$NPM_AUTH_TOKEN"  "env NPM_AUTH_TOKEN is required"

  echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
  echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
