#!/bin/bash

config::git() {
  if [ -n "$CI_PROJECT_URL" ]; then
    # GIT_USER="ci-bot"
    GIT_EMAIL="ci-bot@runner.zcorky.com"
    GIT_REPO=$CI_PROJECT_URL
  fi

  assert "$GIT_USER"  "env GIT_USER is required"
  assert "$GIT_EMAIL" "env GIT_EMAIL is required"
  assert "$GIT_TOKEN" "env GIT_TOKEN is required"
  assert "$GIT_REPO"  "env GIT_REPO is required"

  if [ -n "$CI_PROJECT_URL" ]; then
    zmicro config git "ci-bot" "$GIT_EMAIL"

  else
    zmicro config git $GIT_USER $GIT_EMAIL
  fi

  local GIT_REPO_SCHEMA=$(echo $GIT_REPO | awk -F ':' '{print $1}')
  local GIT_REPO_MAIN=$(echo $GIT_REPO | awk -F '//' '{print $2}')

  git remote set-url origin ${GIT_REPO_SCHEMA}://${GIT_USER}:${GIT_TOKEN}@${GIT_REPO_MAIN}
}

config::npm() {
  assert "$NPM_AUTH_TOKEN"  "env NPM_AUTH_TOKEN is required"

  echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
  echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
}

export -f config::git
export -f config::npm
