#!/bin/bash
function test_vm::os() {
  local expected="unknown-linux-gnu"
  local received=$(vm::os)

  uname -a | grep "Darwin" >> /dev/null 2>&1
  if [ $? == 0 ]; then
    expected="apple-darwin"
  fi
  
  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received" 
}