#!/bin/bash

set -e

help() {
  echo "Finish Builder Pipeline"
  echo ""
  echo "Usage:"
  echo "  builder pipeline finish"
  echo ""
}

core() {
  zmicro builder-node pipeline notify
  zmicro builder-node pipeline clean
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
