#!/bin/bash

set -e

help() {
  echo "Start Builder Pipeline"
  echo ""
  echo "Usage:"
  echo "  builder pipeline start"
  echo ""
}

core() {
  pipeline::start
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
