#!/bin/bash

help() {
  echo "Get Builder Pipeline Status"
  echo ""
  echo "Usage:"
  echo "  builder pipeline status"
  echo ""
}

core() {
  pipeline::status
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
