#!/bin/bash

set -e

help() {
  echo "Success Builder Pipeline"
  echo ""
  echo "Usage:"
  echo "  builder pipeline success"
  echo ""
}

core() {
  pipeline::success
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
